name: Pipeline CI

on:
  push:
    branches: [ main ]

jobs:

  build-test-package:
  
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Instalar dependências
      run: |
        pip install pytest
        pip install build

    - name: Executar testes
      run: pytest

    - name: Build do pacote
      run: python -m build

    - name: Publicar pacote
      run: |
        pip install twine
        python -m twine upload --repository-url https://upload.pypi.org/legacy/dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

    - name: Upload do artefato
      uses: actions/upload-artifact@v4
      with:
        name: pacote-python
        path: dist/
